# Generated by Django 5.0.7 on 2024-10-31 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_petphoto_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
